### ISSUE TITLE
Not working in IE11

### ISSUE THREAD

**Issue by halleycarleton** [anselmh/object-fit#38]
Just tried this out in IE11 and it is not working. It looks like the issue is that `<x-object-fit>` has it's parent container's styling applied to it.

Here's the code:

**HTML**
```html
<div class="img_container img_container-portrait">
  <img class="img-cover" src="https://placeimg.com/640/480/any" alt="" />
</div>
```

**CSS**
```css
body {box-sizing: border-box;}
*, *::before, *::after {position: relative;box-sizing: inherit;}

.img-cover {
  position: absolute;
  top: 0;
  left: 0;
  height: 100%;
  width: 100%;
  object-fit: cover;
}

.img_container {
  width: 50%;
  max-width: 25rem;
  margin: 5rem auto;
  overflow: hidden;
  border: 2px solid #313131;
}

.img_container-portrait::before {
  content: '';
  display: block;
  padding-top: 130%;
}
```

**JS**
```js
window.objectFit.polyfill({
  selector: '.img-cover',
  fittype: 'cover',
  disableCrossDomain: 'false'
});
```

Here is the resulting html:
```html
<div class="img_container img_container-portrait">
  <x-object-fit class="x-object-fit-cover" style="margin: 5rem auto; border: 2px solid rgb(49, 49, 49); border-image: none; width: 50%; overflow: hidden; max-width: 25rem;">
  <img class="x-object-fit-taller" alt="" src="https://placeimg.com/640/480/any" data-x-object-relation="taller">
  </x-object-fit>
</div>
```

You can see that `<x-object-fit>` has the parent's styling in it's style attribute.

[jsfiddle example](http://jsfiddle.net/qL3jzsu8/1/)
